
// Provides `boost::asio::deferred`, a completion token used for lazy/deferred
// initiation of asynchronous operations.
#include "basic_boost.hpp"
#include <boost/asio/associated_allocator.hpp>
#include <boost/asio/associated_executor.hpp>
#include <boost/asio/async_result.hpp>
#include <boost/asio/bind_allocator.hpp>
#include <boost/asio/bind_executor.hpp>
#include <boost/asio/buffer.hpp>
#include <boost/asio/deferred.hpp>
// Provides `boost::asio::io_context`, the core I/O execution context / event
// loop that dispatches completion handlers.
#include <boost/asio/error.hpp>
#include <boost/asio/io_context.hpp>
// Provides TCP networking primitives: `tcp::socket`, `tcp::acceptor`, and
// `tcp::endpoint`.
#include <boost/asio/ip/tcp.hpp>
// Provides `boost::asio::use_future`, a completion token that transforms the
// asynchronous operation into a `std::future`.
#include <boost/asio/post.hpp>
#include <boost/asio/use_future.hpp>
// Provides `boost::asio::async_write`, a high-level composite operation that
// guarantees the entire buffer is written unless an error occurs (unlike
// socket.async_write_some).
#include <boost/asio/write.hpp>
// Standard C/C++ library headers for string length, console output, and move
// semantics.
#include <boost/system/detail/error_code.hpp>
#include <cstddef>
#include <cstring>
#include <functional>
#include <future>
#include <iostream>
#include <memory>
#include <ostream>
#include <sstream>
#include <string>
#include <type_traits>
#include <utility>

namespace compose {
using boost::asio::ip::tcp;
/*
  1. Caller creates handler bound to strand:
   h = bind_executor(my_strand, my_callback);

2. async_write_message creates intermediate_completion_handler:
   struct intermediate_completion_handler {
       handler_ = h;
       get_executor() -> queries h -> returns my_strand
       get_allocator() -> queries h -> returns default or custom allocator
   };

3. boost::asio::async_write begins:
   async_write inspects intermediate_completion_handler
   └──> "Do you have an executor?" -> Yes, get_executor() returns my_strand!

4. I/O completes:
   async_write dispatches intermediate_completion_handler::operator() ON
my_strand. operator() frees the string buffer, then calls handler_(ec) ON
my_strand.
*/
/*
  it call async_write but let user use void(boost::system::error_code) instead
  of void(boost::system::error_code, std::size_t)
*/
template <typename T, typename CompletionToken>
  requires boost::asio::completion_token_for<CompletionToken,
                                             void(boost::system::error_code)> &&
           requires(std::ostream &os, const T &value) { os << value; }
auto async_write_message(tcp::socket &socket, const T &message,
                         CompletionToken &&token) {

  // buffer
  std::ostringstream os;
  os << message;
  auto encoded_message = std::make_unique<std::string>(os.str());
  /*
    the initiation function object is responsible for actually launching the
    underlying asynchronous operation

    it receive :
    a) completion handler: the concrete callback generated by the token
    (match the sig : void(boost::system::error_code))
    b) Any addition arguments passed to 'async_initiate' after the token
  */

  auto initiation =
      [](boost::asio::completion_handler_for<void(
             boost::system::error_code)> auto &&completion_handler,
         tcp::socket &socket_ref, std::unique_ptr<std::string> msg) {
        /*
          every completion handler can have a executor associated with it,
          -if we wrap completion_handler inside std::bind , the resulting
          wrapper loses the inner handler's associated executor traits, asio
          fallback to socket executor or default system executor

          Fix:
          -Query the handler's associated executor (falling back to socket
          executor) -re-attach it to the wrapper using bind_executor
        */

        auto executor = boost::asio::get_associated_executor(
            completion_handler, socket_ref.get_executor());

        auto allocator = boost::asio::get_associated_allocator(
            completion_handler, std::allocator<void>{});

        if (msg->empty()) {
          // post the error asynchronously

          boost::asio::post(boost::asio::bind_allocator(
              allocator,
              boost::asio::bind_executor(
                  executor, [h = std::forward<decltype(completion_handler)>(
                                 completion_handler)]() mutable {
                    h(boost::asio::error::invalid_argument);
                  })));

          return;
        }
        /*
          Intermediate completion handler
          ------------------------------------
          use for underlying `boost::asio::async_write` expects a completion
       signature of: void(boost::system::error_code, std::size_t
       bytes_transferred)
        */
        using Handler = std::decay_t<decltype(completion_handler)>;
        struct intermediate_completion_handler {
          tcp::socket &socket_;
          std::unique_ptr<std::string> msg_;
          Handler handler_;

          void operator()(const boost::system::error_code &error, std::size_t) {
            msg_.reset();
            handler_(error);
          }

          // check for custom executor
          using executor_type = boost::asio::associated_executor_t<
              typename std::decay_t<decltype(completion_handler)>,
              tcp::socket::executor_type>;

          auto get_executor() const noexcept -> executor_type {
            return boost::asio::get_associated_executor(handler_,
                                                        socket_.get_executor());
          }

          // check for custom allocator
          using allocator_type = boost::asio::associated_allocator_t<
              typename std::decay_t<decltype(completion_handler)>,
              std::allocator<void>>;

          auto get_allocator() const noexcept -> allocator_type {
            return boost::asio::get_associated_allocator(
                handler_, std::allocator<void>{});
          }
        };

        auto buffer_view = boost::asio::buffer(*msg);
        boost::asio::async_write(socket_ref, buffer_view,
                                 intermediate_completion_handler{
                                     socket_ref, std::move(msg),
                                     std::forward<decltype(completion_handler)>(
                                         completion_handler)});
      };

  /*
    Delegate to boost::asio::async_initiate
    ----------------------------------------
    async_initiate coordinates the completion token and the initiation step:
    - For callbacks: Immediately construct the handler and invokes 'initiation'
    - For use_future: Create a promise, returns a std::future and invokes
    initiation with a handler that fulfilles the promise
    - For deferred: Packages intiation + arguments into a callable object
    without invoking it yet
  */
  return boost::asio::async_initiate<CompletionToken,
                                     void(boost::system::error_code)>(
      initiation, token, std::ref(socket), std::move(encoded_message));
}

//------------------------------------------------------------------------------
// Test 1: Standard Callback Token (Lambda)
//------------------------------------------------------------------------------
inline void test_callback() {
  std::cout << "\n=== Running test_callback ===\n";
  boost::asio::io_context io_context;
  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  acceptor.set_option(tcp::acceptor::reuse_address(true));
  tcp::socket server_socket(io_context);
  tcp::socket client_socket(io_context);
  client_socket.connect(acceptor.local_endpoint());
  acceptor.accept(server_socket);
  // 1. Success case: passing a number (generic type T)
  async_write_message(
      server_socket, 123456, [](const boost::system::error_code &error) {
        if (!error)
          std::cout << "[Callback] Number sent successfully.\n";
        else
          std::cout << "[Callback] Error: " << error.message() << "\n";
      });
  // 2. Error case: empty message triggers asynchronous invalid_argument
  async_write_message(
      server_socket, "", [](const boost::system::error_code &error) {
        if (!error)
          std::cout << "[Callback] Unexpected: empty message sent.\n";
        else
          std::cout << "[Callback] (Expected) Empty message error: "
                    << error.message() << "\n";
      });
  io_context.run();
}

inline void test_deferred() {
  std::cout << "\n=== Running test_deferred ===\n";
  boost::asio::io_context io_context;
  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  acceptor.set_option(tcp::acceptor::reuse_address(true));
  tcp::socket server_socket(io_context);
  tcp::socket client_socket(io_context);
  client_socket.connect(acceptor.local_endpoint());
  acceptor.accept(server_socket);
  // Packaging the operation lazily: does NOT commence yet!
  boost::asio::async_operation auto op =
      async_write_message(server_socket, std::string("Deferred payload\r\n"),
                          boost::asio::deferred);
  std::cout << "[Deferred] Operation packaged. Launching now...\n";
  // Commencing the operation by supplying the callback
  std::move(op)([](const boost::system::error_code &error) {
    if (!error)
      std::cout << "[Deferred] Message sent successfully.\n";
    else
      std::cout << "[Deferred] Error: " << error.message() << "\n";
  });
  io_context.run();
}

inline void test_future() {
  std::cout << "\n=== Running test_future ===\n";
  boost::asio::io_context io_context;
  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  acceptor.set_option(tcp::acceptor::reuse_address(true));
  tcp::socket server_socket(io_context);
  tcp::socket client_socket(io_context);
  client_socket.connect(acceptor.local_endpoint());
  acceptor.accept(server_socket);
  // Launching operations returning std::future<void>
  std::future<void> f_success =
      async_write_message(server_socket, 987.654, boost::asio::use_future);
  std::future<void> f_error =
      async_write_message(server_socket, "", boost::asio::use_future);
  io_context.run();
  // Verify success future
  try {
    f_success.get();
    std::cout << "[Future] Success future resolved cleanly.\n";
  } catch (const std::exception &e) {
    std::cout << "[Future] Unexpected exception: " << e.what() << "\n";
  }
  // Verify error future throws boost::system::system_error
  try {
    f_error.get();
    std::cout << "[Future] Unexpected: error future succeeded.\n";
  } catch (const std::exception &e) {
    std::cout << "[Future] (Expected) Exception caught: " << e.what() << "\n";
  }
}

void start_compose() {
  test_callback();
  test_deferred();
  test_future();
}
} // namespace compose