
// Provides `boost::asio::deferred`, a completion token used for lazy/deferred
// initiation of asynchronous operations.
#include <boost/asio/associated_executor.hpp>
#include <boost/asio/async_result.hpp>
#include <boost/asio/bind_executor.hpp>
#include <boost/asio/buffer.hpp>
#include <boost/asio/deferred.hpp>
// Provides `boost::asio::io_context`, the core I/O execution context / event
// loop that dispatches completion handlers.
#include <boost/asio/io_context.hpp>
// Provides TCP networking primitives: `tcp::socket`, `tcp::acceptor`, and
// `tcp::endpoint`.
#include <boost/asio/ip/tcp.hpp>
// Provides `boost::asio::use_future`, a completion token that transforms the
// asynchronous operation into a `std::future`.
#include <boost/asio/use_future.hpp>
// Provides `boost::asio::async_write`, a high-level composite operation that
// guarantees the entire buffer is written unless an error occurs (unlike
// socket.async_write_some).
#include <boost/asio/write.hpp>
// Standard C/C++ library headers for string length, console output, and move
// semantics.
#include <boost/system/detail/error_code.hpp>
#include <cstddef>
#include <cstring>
#include <functional>
#include <future>
#include <iostream>
#include <string>
#include <type_traits>
#include <utility>

namespace compose {
using boost::asio::ip::tcp;

/*
  it call async_write but let user use void(boost::system::error_code) instead
  of void(boost::system::error_code, std::size_t)
*/
template <typename CompletionToken>
  requires boost::asio::completion_token_for<CompletionToken,
                                             void(boost::system::error_code)>
auto async_write_message(tcp::socket &socket, const char *message,
                         CompletionToken &&token) {

  /*
    the initiation function object is responsible for actually launching the
    underlying asynchronous operation

    it receive :
    a) completion handler: the concrete callback generated by the token
    (match the sig : void(boost::system::error_code))
    b) Any addition arguments passed to 'async_initiate' after the token
  */

  auto initiation =
      [](boost::asio::completion_handler_for<void(
             boost::system::error_code)> auto &&completion_handler,
         tcp::socket &socket_ref, const char *msg) {
        /*
          every completion handler can have a executor associated with it,
          -if we wrap completion_handler inside std::bind , the resulting
          wrapper loses the inner handler's associated executor traits, asio
          fallback to socket executor or default system executor

          Fix:
          -Query the handler's associated executor (falling back to socket
          executor) -re-attach it to the wrapper using bind_executor
        */

        auto executor = boost::asio::get_associated_executor(
            completion_handler, socket_ref.get_executor());

        /*
          internal of std::bind it take a variadic template and match parameter
          position through std::placeholders , if that position arg is passed it
          is used and rest are disgarded
        */
        auto adapted_handler = std::bind(
            std::forward<decltype(completion_handler)>(completion_handler),
            std::placeholders::_1);

        boost::asio::async_write(
            socket_ref, boost::asio::buffer(msg, std::strlen(msg)),
            boost::asio::bind_executor(executor, std::move(adapted_handler)));
      };

  /*
    Delegate to boost::asio::async_initiate
    ----------------------------------------
    async_initiate coordinates the completion token and the initiation step:
    - For callbacks: Immediately construct the handler and invokes 'initiation'
    - For use_future: Create a promise, returns a std::future and invokes
    initiation with a handler that fulfilles the promise
    - For deferred: Packages intiation + arguments into a callable object
    without invoking it yet
  */
  return boost::asio::async_initiate<CompletionToken,
                                     void(boost::system::error_code)>(
      initiation, token, std::ref(socket), message);
}

void test_callback() {
  boost::asio::io_context io_context;
  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  tcp::socket socket = acceptor.accept();

  async_write_message(socket, "Testing callback\r\n",
                      [](const boost::system::error_code &error) {
                        if (!error) {
                          std::cout << "[Callback] "
                                    << " bytes transferred successfully.\n";
                        } else {
                          std::cout << "[Callback] Error: " << error.message()
                                    << "\n";
                        }
                      });

  io_context.run();
}

void test_deferred() {
  boost::asio::io_context io_context;

  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  tcp::socket socket = acceptor.accept();

  boost::asio::async_operation auto op = async_write_message(
      socket, "Testing deferred\r\n", boost::asio::deferred);
  // Later, we trigger initiation by invoking `op` with our completion handler:
  std::move(op)([](const boost::system::error_code &error) {
    if (!error) {
      std::cout << "[Deferred] " << " bytes transferred successfully.\n";
    } else {
      std::cout << "[Deferred] Error: " << error.message() << "\n";
    }
  });

  io_context.run();
}

void test_future() {

  boost::asio::io_context io_context;
  tcp::acceptor acceptor(io_context, {tcp::v4(), 55555});
  tcp::socket socket = acceptor.accept();
  std::future<void> f = async_write_message(socket, "Testing future\r\n",
                                            boost::asio::use_future);
  io_context.run();
  try {
    // Retrieve the result. Because `io_context.run()` already finished all
    // work, the value is already available and `f.get()` returns immediately
    // without blocking.

    std::cout << " bytes transferred\n";
  } catch (const std::exception &e) {
    // If the socket was closed or an OS error occurred during the write,
    // it arrives here as a `boost::system::system_error`.
    std::cout << "Error: " << e.what() << "\n";
  }
}

void start_compose() {
  test_callback();
  test_deferred();
  test_future();
}
} // namespace compose